# Generated by Django 3.0 on 2022-01-19 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Topic'),
        ),
    ]
