# Generated by Django 3.0 on 2022-01-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220119_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
