# Generated by Django 3.0 on 2022-01-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220124_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profpic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
